// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqghzibymrilgxzvijxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xZ2h6aWJ5bXJpbGd4enZpanh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4MTkwODEsImV4cCI6MjA1OTM5NTA4MX0.RhIyWnHpAjSI4t56ZbEi57Goc_HEose3iYlp3eNIeRE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);